apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: online-boutique-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - recommendationservice
          - checkoutservice
          - paymentservice
          - shippingservice
          - currencyservice
          - productcatalogservice
          - adservice
  endpoints:
  - port: http-metrics
    interval: 15s
    path: /metrics
