apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: compound-recommendation-cpu
  namespace: default
spec:
  mode: one
  selector:
    labelSelectors:
      app: recommendationservice
  stressors:
    cpu:
      workers: 2
      load: 90
  duration: '15m'
