apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: redis-io-latency
  namespace: default
spec:
  action: latency
  mode: one
  selector:
    labelSelectors:
      app: redis-cart
  volumePath: /data
  path: '/**'
  delay: '25ms'
  percent: 100
  duration: '10m'
